version: '3'
services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - 8100:80
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    build: php-fpm/
    container_name: php-fpm
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - 9005:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://php-fpm:9000"]
      interval: 5s
      timeout: 5s
      retries: 5